In [1]:
%cd ..
!ls
%load_ext autoreload

/Users/trippgordon/Desktop/Code/sonic/NoisyGAN
Data        README.md   core        models      submit.sh
Notebooks   __init__.py depricated  notes_ideas train.py


In [2]:
%autoreload 2
%reload_ext autoreload

from core import *
gin.enter_interactive_mode()

INFO:absl:tf versionn: 2.1.0


In [3]:
# input_audio_filepattern = "./Data/piano/piano30s.wav"
output_tfrecord_path = './Data/piano/piano30s.tfrecord'
dataset = DDSP_DATASET(output_tfrecord_path)

# play a sample
# play(dataset.getAudio())

In [4]:
def real_sample_generator(dataset, batch_size=8):
    i = -1
    while True:
        i+=1
        real = next(iter(dataset.data_provider.get_batch(batch_size, shuffle=True, repeats=-1)))
        yield real
        
dataset_iter = real_sample_generator(dataset, batch_size=8)
batch,labels =  next(dataset_iter)
batch

{'audio': <tf.Tensor: shape=(8, 64000), dtype=float32, numpy=
 array([[-0.06819102, -0.06456319, -0.05145652, ..., -0.06995222,
         -0.07926904, -0.08071837],
        [-0.03097209, -0.03147123, -0.03178149, ..., -0.00474663,
          0.0056245 ,  0.01854765],
        [ 0.0610528 ,  0.05943638,  0.05445083, ...,  0.07384819,
          0.0700561 ,  0.06423214],
        ...,
        [ 0.03321686,  0.04797226,  0.06124802, ...,  0.10068679,
          0.09057273,  0.07526067],
        [-0.00372615,  0.00247403,  0.01351822, ..., -0.02428631,
         -0.01310646, -0.002607  ],
        [ 0.00582868,  0.01111687,  0.01333956, ..., -0.0440085 ,
         -0.05466193, -0.05980527]], dtype=float32)>,
 'f0_hz': <tf.Tensor: shape=(8, 1000), dtype=float32, numpy=
 array([[329.54892 , 329.7349  , 329.1455  , ..., 782.3247  , 782.486   ,
         782.1845  ],
        [ 58.111595,  58.063232,  58.049126, ..., 220.36212 , 220.62842 ,
         220.40105 ],
        [294.5771  , 294.37842 , 293.5109 

In [5]:
print(tf.executing_eagerly())

True


In [12]:
model = Discriminator2(batch_size=8)
loss = tf.keras.losses.BinaryCrossentropy()
opt = tf.keras.optimizers.Adam()
model.compile(opt, loss=loss, )
# model(batch)
model.fit(batch,labels)

False
[None 1000 1 30 1]


TypeError: in converted code:

    /Users/trippgordon/Desktop/Code/sonic/NoisyGAN/core/discriminator2.py:28 call  *
        encoded = self.flzEncoder(preprocessed)
    /Users/trippgordon/miniconda3/envs/ddsp/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py:773 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /Users/trippgordon/miniconda3/envs/ddsp/lib/python3.6/site-packages/ddsp/training/encoders.py:51 call  *
        z = self.compute_z(conditioning)
    /Users/trippgordon/miniconda3/envs/ddsp/lib/python3.6/site-packages/ddsp/training/encoders.py:130 compute_z  *
        z = self.z_norm(mfccs[:, :, tf.newaxis, :])[:, :, 0, :]
    /Users/trippgordon/miniconda3/envs/ddsp/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py:773 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    /Users/trippgordon/miniconda3/envs/ddsp/lib/python3.6/site-packages/ddsp/training/nn.py:61 call  *
        x = normalize_op(x, self.norm_type)
    /Users/trippgordon/miniconda3/envs/ddsp/lib/python3.6/site-packages/ddsp/training/nn.py:33 normalize_op  *
        xtf = tf.convert_to_tensor(xnp)
    /Users/trippgordon/miniconda3/envs/ddsp/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1256 convert_to_tensor_v2
        as_ref=False)
    /Users/trippgordon/miniconda3/envs/ddsp/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1314 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /Users/trippgordon/miniconda3/envs/ddsp/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_conversion_registry.py:52 _default_conversion_function
        return constant_op.constant(value, dtype, name=name)
    /Users/trippgordon/miniconda3/envs/ddsp/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py:258 constant
        allow_broadcast=True)
    /Users/trippgordon/miniconda3/envs/ddsp/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py:296 _constant_impl
        allow_broadcast=allow_broadcast))
    /Users/trippgordon/miniconda3/envs/ddsp/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_util.py:558 make_tensor_proto
        append_fn(tensor_proto, proto_values)
    tensorflow/python/framework/fast_tensor_util.pyx:127 tensorflow.python.framework.fast_tensor_util.AppendObjectArrayToTensorProto
        
    /Users/trippgordon/miniconda3/envs/ddsp/lib/python3.6/site-packages/tensorflow_core/python/util/compat.py:87 as_bytes
        (bytes_or_text,))

    TypeError: Expected binary or unicode string, got None


In [7]:
model(batch,batch)

<tf.Tensor: shape=(8, 64000), dtype=float32, numpy=
array([[ 0.27613145,  0.00903034,  0.11031519, ..., -0.00551448,
        -0.14531069, -0.00348957],
       [ 0.28954005,  0.0223361 ,  0.0889401 , ...,  0.19933908,
        -0.1457966 ,  0.09652828],
       [ 0.22078006,  0.3279938 ,  0.28668955, ...,  0.04194896,
        -0.04386936,  0.03513654],
       ...,
       [ 0.32477492,  0.18981722,  0.01392621, ...,  0.03137391,
         0.03093353,  0.01311439],
       [ 0.28139216,  0.01642804,  0.10203525, ...,  0.03115961,
         0.00243242,  0.09300756],
       [ 0.32266116,  0.18977532,  0.01403558, ..., -0.01815234,
        -0.09978849, -0.03499845]], dtype=float32)>