In [1]:
%load_ext autoreload
%cd ..

/Users/trippgordon/Desktop/Code/sonic/NoisyGAN


In [2]:
%autoreload 2
%reload_ext autoreload
from core import *

In [3]:
nsynth_provider = ddsp.training.data.NSynthTfds(split='train')
nsynth_iter = real_sample_iter(nsynth_provider,batch_size=1)
nsynth_batch = next(nsynth_iter)

INFO:absl:Overwrite dataset info from restored data version.
INFO:absl:Constructing tf.data.Dataset for split train, from gs://tfds-data/datasets/nsynth/gansynth_subset.f0_and_loudness/2.3.0


In [4]:
describeSample(nsynth_batch)

pitch: (1,)
audio: (1, 64000)
instrument_source: (1,)
instrument_family: (1,)
instrument: (1,)
f0_hz: (1, 1000)
f0_confidence: (1, 1000)
loudness_db: (1, 1000)


In [3]:
tf_provider = FromTFRecords('./Data/piano/piano30s.tfrecord*')
tf_iter = real_sample_iter(tf_provider,batch_size=8)
tf_batch = next(tf_iter)

In [4]:
describeSample(tf_batch)

audio: (8, 64000)
f0_hz: (8, 1000)
loudness_db: (8, 1000)
label: (8, 1)


In [5]:
tf_provider.getAudio()

<tf.Tensor: shape=(64000,), dtype=float32, numpy=
array([-0.03097209, -0.03147123, -0.03178149, ..., -0.00474663,
        0.0056245 ,  0.01854765], dtype=float32)>

In [8]:
tf.convert_to_tensor([1.0])

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [16]:
tf.ones((8,1))

<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [17]:
tf.zeros((8,1))

<tf.Tensor: shape=(8, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>